name: download-knative

on:
  workflow_dispatch:

jobs:
  download:
    name: download image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: download docker
        run: |
          docker pull ghcr.io/kedacore/keda:2.9.1
          docker tag ghcr.io/kedacore/keda:2.9.1 dazyun/kedacore-keda:2.9.1
          docker pull ghcr.io/kedacore/keda-metrics-apiserver:2.9.1
          docker tag ghcr.io/kedacore/keda-metrics-apiserver:2.9.1 dazyun/keda-metrics-apiserver:2.9.1
          
          docker login -u dazyun -p dckr_pat_ZA5wVlDzq_VAxqJcKhyPy3p0xgM
          docker push dazyun/kedacore-keda:2.9.1
          docker push dazyun/keda-metrics-apiserver:2.9.1
