name: download-knative

on:
  workflow_dispatch:

jobs:
  download:
    name: download image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: download docker
        run: |
          docker pull ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.66.0
          docker tag ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.66.0 dazyun/opentelemetry-collector:0.66.0
          
          docker login -u dazyun -p dckr_pat_ZA5wVlDzq_VAxqJcKhyPy3p0xgM
          docker push dazyun/opentelemetry-collector:0.66.0
