name: download-images

on:
  workflow_dispatch:

jobs:
  download:
    name: download image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: download docker
        run: |
          docker pull nvcr.io/nvidia/k8s-device-plugin:v0.14.0
          docker tag nvcr.io/nvidia/k8s-device-plugin:v0.14.0 dazyun/k8s-device-plugin:v0.14.0

          docker login -u dazyun -p dckr_pat_ZA5wVlDzq_VAxqJcKhyPy3p0xgM
          docker push dazyun/k8s-device-plugin:v0.14.0
