name: download-images

on:
  workflow_dispatch:

jobs:
  download:
    name: download image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: download docker
        run: |
          docker pull gcr.io/kubeflow-images-public/pytorch-operator:v0.6.0
          docker tag gcr.io/kubeflow-images-public/pytorch-operator:v0.6.0 dazyun/pytorch-operator:v0.6.0

          docker login -u dazyun -p dckr_pat_ZA5wVlDzq_VAxqJcKhyPy3p0xgM
          docker push dazyun/pytorch-operator:v0.6.0
