name: download-images

on:
  workflow_dispatch:

jobs:
  download:
    name: download image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: download docker
        run: |
          docker pull registry.k8s.io/descheduler/descheduler:v0.25.1
          docker tag registry.k8s.io/descheduler/descheduler:v0.25.1 dazyun/descheduler:v0.25.1 
          
          docker login -u dazyun -p dckr_pat_ZA5wVlDzq_VAxqJcKhyPy3p0xgM
          docker push dazyun/descheduler:v0.25.1    
