name: download-images

on:
  workflow_dispatch:

jobs:
  download:
    name: download image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: download docker
        run: |
          docker pull registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.5.0
          docker tag registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.5.0 dazyun/kube-state-metrics:v2.5.0

          docker login -u dazyun -p dckr_pat_ZA5wVlDzq_VAxqJcKhyPy3p0xgM
          docker push dazyun/kube-state-metrics:v2.5.0
