name: download-knative

on:
  workflow_dispatch:

jobs:
  download:
    name: download image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: download docker
        run: |
          docker pull gcr.io/knative-nightly/knative.dev/eventing-kafka/cmd/webhook@sha256:0e8cc60cfb6401c8b9cf94deb4c66df5cb550af93783686c358d2e03c325ffad
          docker tag gcr.io/knative-nightly/knative.dev/eventing-kafka/cmd/webhook@sha256:0e8cc60cfb6401c8b9cf94deb4c66df5cb550af93783686c358d2e03c325ffad dazyun/knative-eventing-kafka-webhook:v0.35
          
          docker pull gcr.io/knative-nightly/knative.dev/eventing-kafka/cmd/channel/distributed/controller@sha256:846418c96cfeccdf1c542264dc9e9afc20ba86c84d679ce186153e94a4a5807c
          docker tag gcr.io/knative-nightly/knative.dev/eventing-kafka/cmd/channel/distributed/controller@sha256:846418c96cfeccdf1c542264dc9e9afc20ba86c84d679ce186153e94a4a5807c dazyun/knative-eventing-kafka-channel-controller:v0.35
          
          docker login -u dazyun -p dckr_pat_ZA5wVlDzq_VAxqJcKhyPy3p0xgM
          docker push dazyun/knative-eventing-kafka-webhook:v0.35
          docker push dazyun/knative-eventing-kafka-channel-controller:v0.35
