name: download-images

on:
  workflow_dispatch:

jobs:
  download:
    name: download image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: download docker
        run: |
          docker pull ghcr.io/open-telemetry/demo:1.3.0-shippingservice
          docker tag ghcr.io/open-telemetry/demo:1.3.0-shippingservice dazyun/demo:1.3.0-shippingservice 
          
          docker login -u dazyun -p dckr_pat_ZA5wVlDzq_VAxqJcKhyPy3p0xgM
          docker push dazyun/demo:1.3.0-shippingservice     
          
