name: download

on:
  workflow_dispatch:

jobs:
  download:
    name: download image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: download docker
        run: |
          docker pull gcr.io/knative-releases/knative.dev/operator/cmd/webhook@sha256:30982f8c1e5ec21fece0b170c11a62e5488807ee910c463c2963df6c19e1f368
          docker tag gcr.io/knative-releases/knative.dev/operator/cmd/webhook@sha256:30982f8c1e5ec21fece0b170c11a62e5488807ee910c463c2963df6c19e1f368 dazyun/knative-webhook:v1.6.1
          
          docker pull gcr.io/knative-releases/knative.dev/operator/cmd/operator@sha256:23a267df4c11033fbb862192d713cd0ec46f50cda2a57eb261fff91e9039236b
          docker tag gcr.io/knative-releases/knative.dev/operator/cmd/operator@sha256:23a267df4c11033fbb862192d713cd0ec46f50cda2a57eb261fff91e9039236b dazyun/knative-operator:v1.6.1
          
          docker login -u dazyun -p dckr_pat_ZA5wVlDzq_VAxqJcKhyPy3p0xgM
          docker push dazyun/knative-operator:v1.6.1
          docker push dazyun/knative-webhook:v1.6.1
          
