name: download-knative

on:
  workflow_dispatch:

jobs:
  download:
    name: download image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: download docker
        run: |
          docker pull gcr.io/knative-nightly/knative.dev/eventing-kafka/cmd/channel/distributed/receiver@sha256:eb0baae6624621e5296cdd184217b42404074b6b891f4b5363c2fa7fad52c9b2
          docker tag gcr.io/knative-nightly/knative.dev/eventing-kafka/cmd/channel/distributed/receiver@sha256:eb0baae6624621e5296cdd184217b42404074b6b891f4b5363c2fa7fad52c9b2 dazyun/knative-eventing-kafka-channel-receiver:v0.35
          
          docker pull gcr.io/knative-nightly/knative.dev/eventing-kafka/cmd/channel/distributed/dispatcher@sha256:f6ffe954e24de7559ae00268d11f26da8907f5de72383094bd8bd4ae250e6f13
          docker tag gcr.io/knative-nightly/knative.dev/eventing-kafka/cmd/channel/distributed/dispatcher@sha256:f6ffe954e24de7559ae00268d11f26da8907f5de72383094bd8bd4ae250e6f13 dazyun/knative-eventing-kafka-channel-dispatcher:v0.35
          
          docker login -u dazyun -p dckr_pat_ZA5wVlDzq_VAxqJcKhyPy3p0xgM
          docker push dazyun/knative-eventing-kafka-channel-receiver:v0.35
          docker push dazyun/knative-eventing-kafka-channel-dispatcher:v0.35
