name: download-images

on:
  workflow_dispatch:

jobs:
  download:
    name: download image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: download docker
        run: |
          docker pull registry.k8s.io/ingress-nginx/controller:v1.8.1
          docker tag registry.k8s.io/ingress-nginx/controller:v1.8.1 dazyun/controller:v1.8.1

          docker login -u dazyun -p dckr_pat_ZA5wVlDzq_VAxqJcKhyPy3p0xgM
          docker push dazyun/controller:v1.8.1
