name: download-knative

on:
  workflow_dispatch:

jobs:
  download:
    name: download image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: download docker
        run: |
          docker pull gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping@sha256:e384a295069b9e10e509fc3986cce4fe7be4ff5c73413d1c2234a813b1f4f99b
          docker tag gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping@sha256:e384a295069b9e10e509fc3986cce4fe7be4ff5c73413d1c2234a813b1f4f99b dazyun/knative-serving-domain-mapping:v1.6.1
          
          docker pull gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:813ea20d55b5063596cf967d1c63f51b9e34f883653957157b9b5341dfad0001
          docker tag gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:813ea20d55b5063596cf967d1c63f51b9e34f883653957157b9b5341dfad0001 dazyun/knative-serving-queue:v1.6.1
          
          docker pull docker.io/istio/proxyv2:1.14.1
          docker tag docker.io/istio/proxyv2:1.14.1 dazyun/knative-istio-proxyv2:1.14.1

          docker pull docker.io/istio/pilot:1.14.1
          docker tag docker.io/istio/pilot:1.14.1 dazyun/knative-istio-pilot:1.14.1

          docker pull busybox:1.28
          docker tag busybox:1.28 dazyun/knative-busybox:1.28
          
          docker pull gcr.io/knative-releases/knative.dev/net-istio/cmd/controller@sha256:e8ed74cd7c4839bb83fc4ad005da7742da5bb12145c661ec702df107bda80090
          docker tag gcr.io/knative-releases/knative.dev/net-istio/cmd/controller@sha256:e8ed74cd7c4839bb83fc4ad005da7742da5bb12145c661ec702df107bda80090 dazyun/knative-istio-controller:v1.6.1
          
          docker pull gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook@sha256:148b0ffa1f4bc9402daaac55f233581f7999b1562fa3079a8ab1d1a8213fd909
          docker tag gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook@sha256:148b0ffa1f4bc9402daaac55f233581f7999b1562fa3079a8ab1d1a8213fd909 dazyun/knative-istio-webhook:v1.6.1
          
          docker login -u dazyun -p dckr_pat_ZA5wVlDzq_VAxqJcKhyPy3p0xgM
          docker push dazyun/knative-serving-domain-mapping:v1.6.1
          docker push dazyun/knative-serving-queue:v1.6.1
          docker push dazyun/knative-istio-proxyv2:1.14.1
          docker push dazyun/knative-istio-pilot:1.14.1
          docker push dazyun/knative-busybox:1.28
          docker push dazyun/knative-istio-controller:v1.6.1
          docker push dazyun/knative-istio-webhook:v1.6.1
